<footer class="footer">
	<div class="row">
		<p class="logo"><span class="a11y">유한킴벌리</span></p>
		<div class="info">
			<p>유한킴벌리(주) 사업자정보</p>
			<p>고객센터 <a href="tel:080-500-5200">080-500-5200</a></p>
			<p>평일 09:00 ~ 17:30 / 점심 12:00~13:00</p>
			<p>(주말/공휴일 휴무)</p>
		</div>
	</div>
</footer>

<div class="app_bar">
	<div class="tabs">
		<button class="tab">
			<i class="ic-28 ic_app-home"></i>
			<span>홈</span>
		</button>
		<button class="tab">
			<i class="ic-28 ic_app-search"></i>
			<span>검색</span>
		</button>
		<button class="tab tab-challenge">
			<i class="ic-28 ic_app-challenge"></i>
			<span>오늘<i></i>도전</span>
		</button>
		<button class="tab">
			<i class="ic-28 ic_app-my"></i>
			<span>마이</span>
		</button>
		<button class="tab">
			<i class="ic-28 ic_app-history"></i>
			<span>히스토리</span>
		</button>
	</div>
</div>