<meta charset="UTF-8"/>
  <meta http-equiv="Content-Type" content="text/html"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge, Chrome=1"/>
  <meta http-equiv="Cache-Control" content="No-Cache"/>
  <meta http-equiv="Imagetoolbar" content="no"/>
  <meta content="ALL" name="ROBOTS"/>

	<meta name="twitter:card" content="summary_large_image" />
	<meta name="twitter:site" content="@" />

  <meta name="description" content="오늘플러스, 유한킴벌리, Yuhan-Kimberly"/>
  <meta property="og:title" content="오늘플러스, 유한킴벌리, Yuhan-Kimberly"/>
  <meta property="og:description" content="오늘플러스, 유한킴벌리, Yuhan-Kimberly"/>
	<meta property="og:url" content="@" />
  <meta property="og:image" content="@" />
  <meta name="viewport" id="viewport" content="width=device-width,minimum-scale=1.0,maximum-scale=1.0,initial-scale=1.0"/>
  <title>오늘플러스</title>
  <!-- <link rel="shortcut icon" href="@@webroot/assets/images/common/favicon.ico" type="image/x-icon" />
  <link rel="apple-touch-icon" href="@@webroot/assets/images/common/apple-touch-icon.png" /> -->
  <script type="text/javascript" src="@@webroot/assets/js/jquery-3.4.1.min.js"></script>
  <script type="text/javascript" src="@@webroot/assets/js/ui-plugin.js"></script>
  <link rel="stylesheet" href="@@webroot/assets/css/ui.css"/>
  